# Generated by Django 2.1.2 on 2018-10-06 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181002_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 10, 6, 21, 11, 49, 923097), verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='作者')),
            ],
        ),
    ]
