# Generated by Django 2.1.1 on 2018-10-12 01:37

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181010_2242'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
