# Generated by Django 2.1.1 on 2018-10-21 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='blog.User', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='blog.User', verbose_name='关注'),
        ),
    ]
