# Generated by Django 2.1.1 on 2018-10-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181021_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='create_time',
            field=models.DateTimeField(default='2018-10-21 10:10:30', verbose_name='创建时间'),
        ),
    ]
