# Generated by Django 2.1.1 on 2018-10-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181021_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500, verbose_name='内容')),
                ('create_time', models.DateTimeField(default='2018-10-25 10:10:27', verbose_name='评论时间')),
                ('disabled', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comments', to='blog.User', verbose_name='作者')),
            ],
        ),
        migrations.AlterField(
            model_name='blog_articles',
            name='create_time',
            field=models.DateTimeField(default='2018-10-25 10:10:27', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='create_time',
            field=models.DateTimeField(default='2018-10-25 10:10:27', verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='blog.Blog_Articles', verbose_name='文章'),
        ),
    ]
