# Generated by Django 2.1.1 on 2018-10-26 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181026_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_articles',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
